In [1]:
import numpy as np

In [4]:
var1 = np.array([1,2,3])
print(var1)
var2 = np.array([3,4,6])
print(var2)
print(var1+var2)
print(np.linspace(10,100,10)) #creating numeric sequences
var3= np.array([(1,2,3),(4,5,6),(7,8,9)])
print(var3[0:,2])
print(var3.max()) 
print(var3.sum())
print(var3.sum(axis=0))
print(var3.ravel())
print(np.sqrt(var3))
print(np.std(var1)) #standard deviation means that most of the numbers are close to the mean (average) value


[1 2 3]
[3 4 6]
[4 6 9]
[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[3 6 9]
9
45
[12 15 18]
[1 2 3 4 5 6 7 8 9]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
0.816496580927726
