In [1]:
#Steve Nouri Document

In [2]:
## Why is python numpy better than lists?
#Python numpy arrays should be considered instead of a list because they are fast, 
#consume less memory and convenient with lots of functionality.

In [3]:
##Describe the map function in Python?
#map function executes the function given as the first argument on all theelements of the iterable given as the second argument.

In [8]:
##Generate array of ‘100’ random numbers sampled from a standard normal distribution using Numpy
#np.random.rand(100) will create 100 random numbers generated from standard normal distribution with mean 0 and standard deviation 1.
import numpy as np 
print(np.random.rand(100)) 

[0.03251295 0.74433045 0.90538025 0.87040376 0.94352063 0.79568779
 0.7883777  0.61829207 0.11878659 0.52356244 0.06586536 0.62909984
 0.44159027 0.31478665 0.88164009 0.66797621 0.61340133 0.06029348
 0.33896196 0.7089724  0.37780529 0.46254051 0.34615283 0.72763078
 0.65941602 0.99702117 0.59004016 0.94912156 0.87268026 0.22311348
 0.84574173 0.90913907 0.47533288 0.58068466 0.81799317 0.95526077
 0.19334318 0.07402425 0.96369975 0.04629705 0.23131669 0.10219014
 0.02627307 0.52259474 0.0503016  0.58046687 0.96094654 0.29362784
 0.088615   0.52477082 0.79132968 0.48315031 0.60984387 0.42458181
 0.35373194 0.46350389 0.92570307 0.20524577 0.79707443 0.9654838
 0.98188461 0.13268842 0.13623871 0.42665173 0.06491658 0.58707855
 0.39250745 0.31782763 0.43300895 0.09562093 0.24093976 0.24020404
 0.48255949 0.15363299 0.11432052 0.86205431 0.71550174 0.88825353
 0.43832892 0.25973203 0.06863467 0.84621308 0.25642591 0.41610997
 0.07547121 0.97956976 0.63705041 0.55251546 0.62371061 0.67435

In [10]:
## How to count the occurrence of each value in a numpy array?
import numpy 
arr = numpy.array([0, 5, 5, 0, 2, 4, 3, 0, 0, 5, 4, 1, 9, 9])
print(numpy.bincount(arr))
#This function sorts the numbers,then counts the number of ocourence of each values. Zero means that we have not occourence for a value


[4 1 1 1 2 3 0 0 0 2]


In [13]:
## What does ravel() function in numpy do?
# It combines multiple numpy arrays into a single array
import numpy as np
a= np.array([(1,2,3),(4,5,6),(7,8,9)])
print('\n',a)
print('\n',a.ravel())


 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [1 2 3 4 5 6 7 8 9]


In [18]:
## How to remove from one array those items that exist in another?
import numpy as np
a = np.array([5, 4, 3, 2, 1])
b = np.array([4, 8, 9, 10, 1])
# From 'a' remove all of 'b'
print(np.setdiff1d(a,b))
# From 'b' remove all of 'a'
print(np.setdiff1d(b,a))

[2 3 5]
[ 8  9 10]


In [26]:
## How to sort a numpy array by a specific column in a 2D array?
#Choose column 2 as an example
import numpy as np
arr = np.array([[8, 2, 6], [2, 1, 4], [6,7,3]])
print(arr)
arr[arr[:,1].argsort()]


[[8 2 6]
 [2 1 4]
 [6 7 3]]


array([[2, 1, 4],
       [8, 2, 6],
       [6, 7, 3]])

In [34]:
## How to reverse a numpy array in the most efficient way?
import numpy as np
arr = np.array([9, 10, 1, 2, 0])
reverse_arr = arr[::-1]
print('arr',arr)
print('reverse_arr',reverse_arr)

arr [ 9 10  1  2  0]
reverse_arr [ 0  2  1 10  9]


In [44]:
## How to calculate percentiles when using numpy?
import numpy as np
arr = np.array([11, 22, 33, 44 ,55 ,66, 77])
perc = np.percentile(arr, 40) #Returns the 40th percentile
print(perc)

37.400000000000006


In [45]:
## What Is The Difference Between Numpy And Scipy?

#NumPy would contain nothing but the array data type and the most basic operations:
#indexing, sorting, reshaping, basic element wise functions, et cetera.
#All numerical code would reside in SciPy.
#SciPy contains more fully-featured versions of the linear algebra modules, as well as many other numerical algorithms.

In [55]:
## What Is The Preferred Way To Check For An Empty (zero Element) Array?
# For a numpy array, use the size attribute. The size attribute is helpful for determining the length of numpy array:
import numpy
arr = numpy.zeros((1,0))
print(arr)
arr.size

[]


0

In [56]:
## What Is The Difference Between Matrices And Arrays?

# Matrices can only be two-dimensional, whereas arrays can have any number of dimensions

In [58]:
## How can you find the indices of an array where a condition is true?
# Given an array a, the condition arr > 3 returns a boolean array and since False is interpreted as 0 in Python and NumPy.

import numpy as np
arr = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(arr)
print('\n',arr>3)

[[9 8 7]
 [6 5 4]
 [3 2 1]]

 [[ True  True  True]
 [ True  True  True]
 [False False False]]


In [61]:
## How to find the maximum and minimum value of a given flattened array

import numpy as np
a = np.arange(4).reshape((2,2))
print(a)
max_val = np.amax(a) 
min_val = np.amin(a)
print(min_val,max_val)

[[0 1]
 [2 3]]
0 3


In [67]:
## Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.
import numpy as np
arr = np.arange(16).reshape((4, 4))
print(arr)
res = np.ptp(arr, 1)
print(res)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[3 3 3 3]


In [69]:
## Find median of a numpy flattened array
import numpy as np
arr = np.arange(16).reshape((4, 4))
res = np.median(arr)
print(arr)
print(res)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
7.5


In [76]:
##Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis
#Mean : The mean(average) of a dataset is found by adding all numbers in the data set and then deviding by the values in the set
#Median:The  median is the middle value when a data set is orderd  from least to greatest
#Variance VS standard deviation is the average squared deviations from the mean, while standard deviation is the square root of this number
# A standard deviation is a measure of how dispersed the data in relation to the mean.
 #low standard deviation means data are clustered around the mean,high standard deviation indicates data are more spread out
    
import numpy as np
x = np.arange(16)
mean = np.mean(x)
std = np.std(x)
var= np.var(x)
median=np.median(x)
print(x)
print('mean =',mean)
print('standard deviation =',std)
print('variance =',var)
print('median =',median)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
mean = 7.5
standard deviation = 4.6097722286464435
variance = 21.25
median = 7.5


In [80]:
##Calculate covariance matrix between two numpy arrays
import numpy as np
x = np.array([2, 1, 0])
y = np.array([2, 3, 3])
cov_arr = np.cov(x, y)
print('\n',x)
print('\n',y)
print('\n',cov_arr)


 [2 1 0]

 [2 3 3]

 [[ 1.         -0.5       ]
 [-0.5         0.33333333]]


In [82]:
## Compute Compute pearson product-moment correlation coefficients of two given numpy arrays
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
cross_corr = np.corrcoef(x, y)
print(cross_corr)


[[1.         0.92857143]
 [0.92857143 1.        ]]


In [85]:
## Develop a numpy program to compute the histogram of nums against the bins
import numpy as np
nums = np.array([0.5, 0.7, 1.0, 1.2, 1.3, 2.1])
bins = np.array([0, 1, 2, 3])
np.histogram(nums, bins)

(array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))

In [87]:
## Get the powers of an array values element-wise
import numpy as np
x = np.arange(7)
print(x)
print(np.power(x, 3))

[0 1 2 3 4 5 6]
[  0   1   8  27  64 125 216]


In [88]:
##Write a NumPy program to get true division of the element-wise array inputs
import numpy as np
x = np.arange(10)
print(x)
print(np.true_divide(x, 3))


[0 1 2 3 4 5 6 7 8 9]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]
